### PR TITLE
Reorganized folders following IHEC Annual Meeting 2017 proposal.

### PR DESCRIPTION
**Pull request by dbujold**

### CODE REVIEW

**Comment by sitag** [comment]
Can we do a release before we merge in this request?

**Comment by tsierocinski** [comment]
Can my email address be removed from this mailing list please?

Thank you.

Thomas


On Oct 17, 2017 5:09 PM, "sitag" <notifications@github.com> wrote:

Can we do a release before we merge in this request?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IHEC/ihec-assay-standards/pull/3#issuecomment-337416948>,
or mute the thread

**Comment by dbujold** [comment]
Hi Thomas, if you're talking about GitHub notifications, you have to 
remove yourself as a watcher in the ASWG GitHub.

Sincerely,

David

**Comment by dbujold** [comment]
Sure can, although isn't it better to do the cleanup beforehand? Or 
should we tag the current version 0.1, and then merge the PR in master, 
in preparation for version 1?

Thanks,

David

**Comment by sitag** [comment]
Since things will move around quite a bit, in case someone needs it, it would be good to have a snapshot of how things are before this happens for easy reference (as vs digging through commits). Releasing in this state is not idea - but maybe there's another way to tag the state prior to the merge?

**Comment by dbujold** [comment]
Hi Sita, what would you think of creating Git tags for new versions that 
would correspond to annual IHEC meetings? So the current version, 
pre-merge, would be tag "2017-10-12". That would allow us to see what 
was done before reshuffling things around. And then the next tag could 
be at next year's meeting, or before that if we decide that we've 
reached a big enough milestone.

Thank you,

David

**Comment by sitag** [comment]
Thanks, David. That sounds like a good plan.

**Pull request merged**
